# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41

---
include:
    - board: nice_nano_v2
      shield: 3x5_2_left
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 3x5_2_right
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 2_3x4_2_left
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 2_3x4_2_right
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23332_2_left
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23332_2_right
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23332_2_pc_left
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23332_2_pc_right
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23331_2_left
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23331_2_right
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23331_2_pc_left
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 23331_2_pc_right
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 2333_2_left
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: 2333_2_right
      # snippet: zmk-usb-logging
    - board: nice_nano_v2
      shield: settings_reset
      # snippet: zmk-usb-logging
