# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#     - name: caksoylar
#       url-base: https://github.com/caksoylar
#   projects:
#     - name: zmk
#       remote: caksoylar
#       revision: caksoylar/zen-8bit
#       import: app/west.yml
#   self:
#     path: config

manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
  self:
    path: config